grammar : expression grammar
        |

code_block : compound_statements

compound_statements : compound_statement compound_statements
                    |

compound_statement : if_statement
                   | loop_statement
                   | expression

expression : NUMBER
           | operator
           | comparison_operator
           | function
           | LITERAL
           | PRINT_STRING
           | CHAR_FUNC
           | VARIABLE_DECLARATION LITERAL
           | LITERAL STORE
           | LITERAL FETCH

operator : PLUS
         | MINUS
         | TIMES
         | DIVIDE
         | EXP
         | MOD
         | SLASH_MOD

comparison_operator : EQUALS
                    | NOT_EQUALS
                    | LESS_THAN
                    | LESS_THAN_OR_EQUAL_TO
                    | GREATER_THAN
                    | GREATER_THAN_OR_EQUAL_TO
                    | ZERO_EQUALS
                    | ZERO_LESS_THAN
                    | ZERO_LESS_THAN_OR_EQUAL_TO
                    | ZERO_GREATER_THAN
                    | ZERO_GREATER_THAN_OR_EQUAL_TO

function : COLON LITERAL code_block SEMI_COLON

if_statement : IF code_block THEN
             | IF code_block ELSE code_block THEN

loop_statement : DO code_block LOOP
               | DO code_block PLUS_LOOP
